---
title: "Chapter7_Fede"
author: "Federico Andrade-Rivas"
date: "January 29, 2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Loading Libraries

```{r library}
library(tidyverse)
library(gapminder)
```


##Create a copy of gapminder

``` {r copyGap}
library(gapminder)
my_gap <-gapminder
my_gap %>% filter(country == "Canada")  

#Storing the output as an object

my_precious <- my_gap %>% filter(country =="Canada")

```

``` {r Mutate}
 my_gap %>% mutate(gdp = pop*gdpPercap)

# Create a new variable that is gdpPercap divided by Canadian gdpPercap, taking care that I always divide two numbers that pertain to the same year

cgdp <- my_gap %>% filter(country =="Canada")

my_gap <- my_gap %>% mutate(temp = rep(cgdp$gdpPercap, nlevels(country)),
                            gdpRelaC = gdpPercap/temp,
                            temp = NULL
                            )
#Note: nlevels is used to create a variable that is as long as the number of levels per country. All countries have data for the same years. Otherwise this would not work 

my_gap %>%  filter(country == "Canada") %>% select(country, year, gdpPercap, gdpRelaC)

#Distribution of gdp related with the Canadian one

summary(my_gap$gdpRelaC)


```
#!!!!Remember: Trust No One. Including (especially?) yourself. Always try to find a way to check that you’ve done what meant to. Prepare to be horrified.

##Arrange function
```{r arrange}
#Use arrange() to row-order data in a principled way
#Example to arrange by year then country
my_gap %>% arrange(year, country)

#Example to arrange by continent then country
my_gap %>% arrange(continent, country)

#example one year but sorted by life expectancy
 my_gap %>% filter(year == 1952) %>% arrange(gdpPercap) %>% select(country, continent, year, gdpPercap)

 #NOw in descending order for 2007
 
 my_gap %>% filter(year == 2007) %>% arrange(desc(gdpPercap)) %>% select(country, continent, year, gdpPercap)

 #"I advise that your analyses NEVER rely on rows or variables being in a specific order. But it’s still true that human beings write the code and the interactive development process can be much nicer if you reorder the rows of your data as you go along. Also, once you are preparing tables for human eyeballs, it is imperative that you step up and take control of row order."
```

##Rename, Select, and Group by

```{r Ch7rename}
#camelCase Vs snake_case
#Rename variables (not assigning!)

my_gap %>% rename(life_exp = lifeExp,
                  gdp_percap = gdpPercap,
                  gdp_percap_rel = gdpRelaC)

#select can rename and reposition 
#select() can rename the variables you request to keep.
#select() can be used with everything() to hoist a variable up to the front of the tibble.

my_gap %>% 
  filter(country == "Burundi", year > 1996) %>% 
  select(yr = year, life_exp = lifeExp, gdp_Percap = gdpPercap) %>% 
  select(gdp_Percap, everything())

#Counting things up

my_gap %>% 
  group_by(continent) %>% 
  summarize(n = n())

#Same info as R base table() but issues with computing

table(my_gap$continent)

#tally() counts rows

my_gap %>% 
  group_by(continent) %>% 
  tally()

#The count() function is an even more convenient function that does both grouping and counting.

my_gap %>% 
  count(continent) 

#Use the n_distinct() function to count the number of distinct countries within each continent.

my_gap %>% 
  group_by(continent) %>% 
  summarize(n = n(),
            n_countries = n_distinct(country))

#general summarization
my_gap %>% 
  group_by(continent) %>% 
  summarize(avg_lifeExp = mean(lifeExp))

#using summarize at (applies several functions)

my_gap %>% 
  filter(year %in% c(1952,2007)) %>% 
  group_by(continent, year) %>% 
  summarize_at(vars(lifeExp,gdpPercap), list(~mean(.), ~median(.), ~sd(.)))

# Minimun and maximun lifeExp seen by year. In Asia

my_gap %>% 
  filter(continent == "Asia") %>% 
  group_by(year) %>% 
  summarize(lifeExpmin = min(lifeExp), lifeExpmax = max(lifeExp))


```

##GROUP MUTATE
```{r GroupMutate}
#computing with group-wise summaries
#EXample, year of life exp gained relative to 1952 per country.

my_gap %>% 
  group_by(country) %>% 
  select(country, year, lifeExp) %>% 
  mutate(lifeExp_gain = lifeExp - first(lifeExp)) %>% 
  filter(year < 1963, year > 1952)
  
#Windows functions
#ASi worst and best in Life exp, but retaining infor countries

my_gap %>% 
  filter(continent =="Asia") %>% 
  select(year, country, lifeExp) %>%   
  group_by(year) %>% 
  filter(min_rank(desc(lifeExp)) < 2 | min_rank(lifeExp) < 2) %>% 
    arrange(year) %>% 
    print(n=Inf)
    
```

```{r GrandFinale}
#Sharpest drop lifeExp in 5 years , By continent

my_gap %>% 
  select(country, year, continent, lifeExp) %>% 
  group_by(continent, country) %>%
  ## within country, take (lifeExp in year i) - (lifeExp in year i - 1)
  ## positive means lifeExp went up, negative means it went down
  mutate(le_delta = lifeExp - lag(lifeExp)) %>% 
  ## within country, retain the worst lifeExp change = smallest or most negative
  summarize(worst_le_delta = min(le_delta, na.rm =TRUE)) %>% 
  ## within continent, retain the row with the lowest worst_le_delta
   #In this case the top(-2) indicates to take two min values of the variable. 
  top_n(-2, wt = worst_le_delta) %>% 
arrange(worst_le_delta)
  


```


```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
